services:

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: weight-project-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: weight-project-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  database:
    image: mariadb:10.11
    container_name: weight-project-db
    environment:
      MARIADB_DATABASE: weight_project
      MARIADB_USER: weight
      MARIADB_PASSWORD: weight
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  mailer:
    image: axllent/mailpit
    container_name: weight-project-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database_data: